#!/bin/bash

# convert dotted-decimal subnet mask to CIDR notation
mask2cidr() {
	nbits=0
	IFS=.
	
	for dec in $1; do
		case $dec in
			0) ;;
			128) let nbits+=1 ;;
			192) let nbits+=2 ;;
			224) let nbits+=3 ;;
			240) let nbits+=4 ;;
			248) let nbits+=5 ;;
			252) let nbits+=6 ;;
			254) let nbits+=7 ;;
			255) let nbits+=8 ;;
			*) >&2 echo "mask2cidr(): $dec not recognized"; exit 1 ;;
		esac
	done
	echo "/$nbits"
}

echo $(mask2cidr $1)
